version: "3"
services:
  jupyterlab:
    build: .
    container_name: jupyterlab
    volumes:
      - /mnt/d/Work:/home/host # マウントするフォルダ
    working_dir: /home # コンテナ内の初期ディレクトリ
    ports:
      - 8888:8888 #ポート設定 / 手元のポート:コンテナのポート
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''
    #command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser
